import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "@/components/context/ThemeContext";
import ThemeIndicator from "@/components/ThemeIndicator";
import ClientThemeWrapper from "@/components/context/CliehtThemeWrapper";
import NavbarHeader from "@/components/NavbarHeader";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Alexvarelo.raw</title>
        <meta name="description" content="My personal photo portfolio" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          <ClientThemeWrapper>
            <NavbarHeader />
            <div className="flex flex-col min-h-screen">
              <div className="flex-grow container mx-auto p-4">{children}</div>
            </div>
            <Footer />
          </ClientThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
