import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "@/components/context/ThemeContext";
import ThemeIndicator from "@/components/ThemeIndicator";
import ClientThemeWrapper from "@/components/context/CliehtThemeWrapper";
import NavbarHeader from "@/components/NavbarHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ClientThemeWrapper>
            <NavbarHeader />
            <div className="container mx-auto p-4">{children}</div>
          </ClientThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
